name: LittleRPG
main: littlegruz.arpeegee.ArpeegeeMain
version: 0.1

commands:
   addclass:
      description: Adds a new class
      usage: /addclass <name> <strength> <accuracy> <intelligence>
   addsubclass:
      description: Adds a new sub-class
      usage: /addsubclass <name> <archery> <blade> <block> <egg> <spell>
   removeclass:
      description: Removes a new class
      usage: /removeclass <name>
   removesubclass:
      description: Removes a new sub-class
      usage: /removesubclass <name>
   displayclass:
      description: Removes a new class
      usage: /dispayclass [name]
   displaysubclass:
      description: Removes a new class
      usage: /displaysubclass [name]
      
permissions:
   arpeegee.create:
      description: Creating [sub-]classes
      default: op
   arpeegee.remove:
      description: Removing [sub-]classes
      default: op
   arpeegee.display:
      description: Displaying [sub-]classes
      default: true