name: LittleRPG
main: littlegruz.arpeegee.ArpeegeeMain
version: 0.1

commands:
   displayclass:
      description: Displays all classes or the stats of just one
      usage: /dispayclass [name]
   displaysubclass:
      description: Displays all sub-classes or the stats of just one
      usage: /displaysubclass [name]
   iammelee:
      description: Sets your class as melee
      usage: /iammelee
   iamranged:
      description: Sets your class as ranged
      usage: /iamranged
   iammagic:
      description: Makes it all complete
      usage: /iammagic
      
permissions:
   arpeegee.create:
      description: Creating [sub-]classes
      default: op
   arpeegee.remove:
      description: Removing [sub-]classes
      default: op
   arpeegee.display:
      description: Displaying [sub-]classes
      default: true
   arpeegee.begin:
      description: Choosing starting classes
      default: true