name: LittleRPG
main: littlegruz.arpeegee.ArpeegeeMain
version: 0.1

commands:
   displaysubclass:
      description: Displays all sub-classes or the stats of just one
      usage: /displaysubclass [name]
   ichoosemelee:
      description: Sets your class as melee
      usage: /ichoosemelee
   ichooseranged:
      description: Sets your class as ranged
      usage: /ichooseranged
   ichoosemagic:
      description: Makes it all complete
      usage: /ichoosemagic
      
permissions:
   arpeegee.create:
      description: Creating [sub-]classes
      default: op
   arpeegee.remove:
      description: Removing [sub-]classes
      default: op
   arpeegee.display:
      description: Displaying [sub-]classes
      default: true
   arpeegee.begin:
      description: Choosing starting classes
      default: true