name: LittleRPG
main: littlegruz.arpeegee.ArpeegeeMain
version: 1.0

commands:
   displaysubclass:
      description: Displays all sub-classes or the stats of just one
      usage: /displaysubclass [name]
   ichoosemelee:
      description: Sets your class as melee
      usage: /ichoosemelee
   ichooseranged:
      description: Sets your class as ranged
      usage: /ichooseranged
   ichoosemagic:
      description: Makes it all complete
      usage: /ichoosemagic
   addrpgworld:
      description: Adds the current world to the list of worlds affected by the plugin
      usage: /addrpgworld
   removerpgworld:
      description: Removes the current world to the list of worlds affected by the plugin
      usage: /removerpgworld
      
permissions:
   arpeegee.world:
      description: Adding or removing worlds where LittleRPG is active
      default: op
   arpeegee.display:
      description: Displaying [sub-]classes
      default: true
   arpeegee.begin:
      description: Choosing starting classes
      default: true